name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      VITE_GAMES_URL: ${{ secrets.VITE_GAMES_URL }}
      VITE_LOKI_USER: ${{ secrets. VITE_LOKI_USER }}
      VITE_LOKI_API_KEY: ${{ secrets.VITE_LOKI_API_KEY }}
      VITE_LOKI_URL: ${{ secrets.VITE_LOKI_URL }}

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.3.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm test
